# Contains personal customisations of Rubocop default rules
require: rubocop-rspec

AllCops:
  Exclude:
    # NOTE: binstubs seem to be re-generating after every bundle, so I'm going
    # to consider code in them not my responsibility.
    - "bin/**/*"
    # NOTE: Although this exclusion is in the default Rubocop config, it seems
    # that CI still goes looking in the vendor directory and attempts to
    # scan all files in all gems, so make the exclusion explicit here.
    - "vendor/**/*"
  NewCops: enable
  TargetRubyVersion: 3.0

# NOTE: This app makes use of Pry directly in the code, so seeing it left
# in the codebase is expected.
Lint/Debugger:
  Enabled: false

# NOTE: Default is 10
Metrics/MethodLength:
  Max: 17

# NOTE: Default is 1
RSpec/MultipleExpectations:
  Max: 4

# NOTE: Default is 5
RSpec/MultipleMemoizedHelpers:
  Max: 6

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: "double_quotes"
  ConsistentQuotesInMultiline: true
