# Contains personal customisations of Rubocop default rules
require: rubocop-rspec

AllCops:
  Exclude:
    - "resume.rb"
    - "strings_en.rb"
    - "strings_it.rb"
    - "strings_ja.rb"
    # NOTE: Although this exclusion is in the default Rubocop config, it seems
    # that CI still goes looking in the vendor directory and attempts to
    # scan all files in all gems, so make the exclusion explicit here.
    - "vendor/**/*"
  TargetRubyVersion: 2.3

# NOTE: This app makes use of Pry directly in the code, so seeing it left
# in the codebase is expected.
Lint/Debugger:
  Enabled: false

# NOTE: Default is 15
Metrics/AbcSize:
  Max: 17

# NOTE: Default is 10
Metrics/MethodLength:
  Max: 17

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*"

# NOTE: Default is 1
RSpec/MultipleExpectations:
  Max: 4

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/FirstArrayElementLineBreak:
  Enabled: true

Style/FirstHashElementLineBreak:
  Enabled: true

Style/FirstMethodArgumentLineBreak:
  Enabled: true

Style/FirstMethodParameterLineBreak:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: true

Style/InlineComment:
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: new_line

Style/MultilineMethodCallIndentation:
  Exclude:
    - "spec/**/*"

Style/OptionHash:
  Enabled: true

Style/Send:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/StringMethods:
  Enabled: true

Style/SymbolArray:
  Enabled: true
