# References:
# - https://docs.travis-ci.com/user/caching/#Bundler
sudo: false
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.6.3
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
before_install:
  - gem update --system
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  # NOTE: coverage directory has a habit of being cached and potentially added
  # to when you want to create it anew, so delete it every run.
  - rm -rf coverage
  - bin/rake
  - bin/rubocop
after_success:
  # Send results to Code Climate
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
