# References:
# - https://docs.travis-ci.com/user/caching/#Bundler
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.2
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
before_install:
  - gem update --system
script:
  - rm -rf coverage
  - bin/rake
  - bin/rubocop
after_success:
  - bin/codeclimate-test-reporter
