# References:
# - https://docs.travis-ci.com/user/caching/#Bundler
sudo: false
language: ruby
cache: bundler
rvm:
- 2.3.1
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
script:
- bin/rake
